# Generated by Django 2.0.7 on 2018-08-21 08:41

from django.db import migrations
import drfaddons.datatypes


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='update_date',
            field=drfaddons.datatypes.UnixTimestampField(auto_created=True, auto_now_add=True),
        ),
    ]
