# Generated by Django 2.0.7 on 2018-08-24 13:40

from django.db import migrations
import drfaddons.datatypes


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0003_auto_20180824_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=drfaddons.datatypes.UnixTimestampField(auto_now=True),
        ),
    ]
